# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-04 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_mg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='picture',
            field=models.ImageField(null=True, upload_to='artpicture', verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='user',
            name='head_sculpture',
            field=models.ImageField(null=True, upload_to='userpicture', verbose_name='用户头像'),
        ),
    ]
