# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-04 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_mg', '0002_auto_20181204_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
    ]
