# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-06 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_mg', '0006_auto_20181205_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='isRelease',
            field=models.BooleanField(default=1),
        ),
    ]
